import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,ZeroAddress} from 'ethers';
import {compile} from '../../scripts/contracts/compile.mjs';
let compiled, rpc, provider, signers;
before(async()=>{compiled=compile(true);rpc=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai'},wallet:{totalAccounts:8}});provider=new BrowserProvider(rpc);provider.pollingInterval=10;signers=await Promise.all(Array.from({length:8},(_,i)=>provider.getSigner(i)));});
after(async()=>{provider.destroy();await rpc.disconnect();});
const sent=async p=>{const tx=await p;await tx.wait();return tx;};
async function deploy(file,name,args=[]){const c=compiled[file][name];const x=await new ContractFactory(c.abi,c.evm.bytecode.object,signers[0]).deploy(...args);await x.waitForDeployment();return x;}
async function fixture(d=18){const token=await deploy('contracts/test/Mocks.sol','MockToken',[d]);const vault=await deploy('contracts/ClunkVault.sol','ClunkVault',[await token.getAddress(),await signers[0].getAddress(),'ipfs://collection/']);const amount=50000n*10n**BigInt(d);await sent(vault.setMintOpen(true));for(let i=1;i<=3;i++){await sent(token.faucet(await signers[i].getAddress(),amount*2n));await sent(token.connect(signers[i]).approve(await vault.getAddress(),amount));}return {token,vault,amount};}
async function rejects(p){await assert.rejects(p);}
test('starts closed; administrator cannot withdraw backing and only owner opens mint',async()=>{
 const t=await deploy('contracts/test/Mocks.sol','MockToken',[18]);const v=await deploy('contracts/ClunkVault.sol','ClunkVault',[await t.getAddress(),await signers[0].getAddress(),'ipfs://collection/']);
 assert.equal(await v.mintOpen(),false);await rejects(v.connect(signers[1]).mint(1));await rejects(v.connect(signers[1]).setMintOpen(true));assert.equal(v.interface.hasFunction('withdraw'),false);
});
test('mint locks exactly 50,000 tokens, creates one NFT and stable metadata',async()=>{const {token,vault,amount}=await fixture();await sent(vault.connect(signers[1]).mint(1));assert.equal(await vault.ownerOf(1),await signers[1].getAddress());assert.equal(await token.balanceOf(await vault.getAddress()),amount);assert.equal(await vault.totalBacking(),amount);assert.equal(await vault.tokenURI(1),'ipfs://collection/1.json');assert.equal(await vault.nextAvailableId(),2n);});
test('six-decimal token receives the exact same whole-token backing',async()=>{const {token,vault,amount}=await fixture(6);await sent(vault.connect(signers[1]).mint(1));assert.equal(await vault.backingAmount(),50000000000n);await sent(vault.connect(signers[1]).redeem(1));assert.equal(await token.balanceOf(await vault.getAddress()),0n);assert.equal(await token.balanceOf(await signers[1].getAddress()),amount*2n);});
test('no allowance / insufficient balance / stale expected identity cannot collect tokens or consume opportunity',async()=>{
 const {token,vault,amount}=await fixture();await sent(token.connect(signers[1]).approve(await vault.getAddress(),0));await rejects(vault.connect(signers[1]).mint(1));assert.equal(await vault.directMintUsed(await signers[1].getAddress()),false);
 await rejects(vault.connect(signers[4]).mint(1));await rejects(vault.connect(signers[2]).mint(9));assert.equal(await token.balanceOf(await vault.getAddress()),0n);assert.equal(await token.balanceOf(await signers[2].getAddress()),amount*2n);
});
test('lifetime mint stays consumed after transfer and redemption; only current owner redeems',async()=>{const {token,vault,amount}=await fixture();const a=await signers[1].getAddress(),b=await signers[2].getAddress();await sent(vault.connect(signers[1]).mint(1));await sent(vault.connect(signers[1])['safeTransferFrom(address,address,uint256)'](a,b,1));await rejects(vault.connect(signers[1]).mint(2));await rejects(vault.connect(signers[1]).redeem(1));await sent(vault.connect(signers[2]).redeem(1));assert.equal(await token.balanceOf(b),amount*3n);await rejects(vault.connect(signers[1]).mint(1));assert.equal(await vault.nextAvailableId(),1n);await sent(vault.connect(signers[3]).mint(1));assert.equal(await vault.ownerOf(1),await signers[3].getAddress());assert.equal(await vault.totalSupply(),1n);});
test('approved NFT operator cannot redeem someone else’s backing',async()=>{const {vault}=await fixture();await sent(vault.connect(signers[1]).mint(1));await sent(vault.connect(signers[1]).approve(await signers[2].getAddress(),1));await rejects(vault.connect(signers[2]).redeem(1));});
test('pausing new mints leaves transfers and redemption working',async()=>{const {vault}=await fixture();await sent(vault.connect(signers[1]).mint(1));await sent(vault.setMintOpen(false));await rejects(vault.connect(signers[2]).mint(2));await sent(vault.connect(signers[1])['safeTransferFrom(address,address,uint256)'](await signers[1].getAddress(),await signers[2].getAddress(),1));await sent(vault.connect(signers[2]).redeem(1));assert.equal(await vault.totalBacking(),0n);});
test('fee-on-transfer deposits revert atomically',async()=>{const {token,vault,amount}=await fixture();await sent(token.setTax(true));await rejects(vault.connect(signers[1]).mint(1));assert.equal(await token.balanceOf(await signers[1].getAddress()),amount*2n);assert.equal(await vault.directMintUsed(await signers[1].getAddress()),false);assert.equal(await vault.totalSupply(),0n);});
test('taxed redemption reverts without burning NFT or losing reserve',async()=>{const {token,vault,amount}=await fixture();await sent(vault.connect(signers[1]).mint(1));await sent(token.setTax(true));await rejects(vault.connect(signers[1]).redeem(1));assert.equal(await vault.ownerOf(1),await signers[1].getAddress());assert.equal(await token.balanceOf(await vault.getAddress()),amount);});
test('reentrant receiver cannot redeem inside mint callback',async()=>{const {token,vault,amount}=await fixture();const r=await deploy('contracts/test/Mocks.sol','ReentrantReceiver',[await vault.getAddress()]);await sent(token.faucet(await r.getAddress(),amount));await sent(r.run(await token.getAddress()));assert.equal(await r.attempted(),true);assert.equal(await vault.ownerOf(1),await r.getAddress());assert.equal(await token.balanceOf(await vault.getAddress()),amount);});
test('rejecting receiver rolls back NFT, allowance use, deposit and lifetime mint',async()=>{const {token,vault,amount}=await fixture();const r=await deploy('contracts/test/Mocks.sol','RejectReceiver');await sent(token.faucet(await r.getAddress(),amount));await rejects(r.run(await token.getAddress(),await vault.getAddress()));assert.equal(await vault.directMintUsed(await r.getAddress()),false);assert.equal(await token.balanceOf(await r.getAddress()),amount);assert.equal(await vault.totalSupply(),0n);});
test('invalid token and excessive decimals cannot deploy; 300 identity ceiling is immutable',async()=>{await rejects(deploy('contracts/ClunkVault.sol','ClunkVault',[ZeroAddress,await signers[0].getAddress(),'ipfs://collection/']));const t=await deploy('contracts/test/Mocks.sol','MockToken',[37]);await rejects(deploy('contracts/ClunkVault.sol','ClunkVault',[await t.getAddress(),await signers[0].getAddress(),'ipfs://collection/']));const {vault}=await fixture();assert.equal(await vault.MAX_IDENTITIES(),300n);});
test('300 real mints exhaust pool; mint 301 reverts and full reserve is exact',async()=>{
 const {token,vault,amount}=await fixture();const batch=await deploy('contracts/test/Mocks.sol','BatchMint');
 for(let i=0;i<30;i++)await sent(batch.run(await token.getAddress(),await vault.getAddress(),10,{gasLimit:25000000}));
 assert.equal(await vault.totalSupply(),300n);assert.equal(await vault.nextAvailableId(),0n);assert.equal(await token.balanceOf(await vault.getAddress()),300n*amount);await rejects(vault.connect(signers[1]).mint(301));assert.equal(await vault.directMintUsed(await signers[1].getAddress()),false);
});
