import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRevealHandler} from '../../server/reveal.mjs';
const record={entry:{id:1,name:'Secret identity',attributes:[{trait_type:'Rarity',value:'Legendary'}]},metadata:{name:'Secret identity',attributes:[{trait_type:'Rarity',value:'Legendary'}]},svg:'<svg>SECRET_ART</svg>',thumbnail:btoa('SECRET_THUMB')};
const config={vaultAddress:'0x'+'2'.repeat(40),rpcUrl:'https://rpc.invalid',chainId:999,confirmations:2,deploymentBlock:1};
function setup({owned=[1],chain='0x3e7',failure=false}={}){const blocks=[];const handler=createRevealHandler({records:{1:record},config,rpcFetch:async(_,options)=>{if(failure)throw new Error('offline');const calls=JSON.parse(options.body);return Response.json(calls.map(c=>{if(c.method==='eth_chainId')return {id:c.id,result:chain};if(c.method==='eth_blockNumber')return{id:c.id,result:'0x64'};blocks.push(c.params[1]);const id=Number(BigInt('0x'+c.params[0].data.slice(10)));return owned.includes(id)?{id:c.id,result:'0x'+'0'.repeat(24)+'1'.repeat(40)}:{id:c.id,error:{code:3,message:'execution reverted'}};}).reverse());}});return{handler,blocks};}
const req=path=>new Request('https://clunk.lat'+path);
test('unconfigured service never discloses data or requests RPC',async()=>{const h=createRevealHandler({records:{1:record},config:{},rpcFetch:()=>{throw new Error('must not call')}});const meta=await h(req('/nft/metadata/1.json'));assert.deepEqual((await meta.json()).attributes,[]);assert.equal((await h(req('/nft/art/001.svg'))).status,302);assert.deepEqual(await (await h(req('/nft/revealed?ids=1'))).json(),{entries:[]});});
test('unminted direct URLs, thumbnails and metadata remain concealed',async()=>{const{handler}=setup({owned:[]});for(const path of ['/nft/art/001.svg','/nft/thumbs/001.webp']){const r=await handler(req(path));assert.equal(r.status,302);assert.match(r.headers.get('location'),/brand/);}const r=await handler(req('/nft/metadata/1.json'));const data=await r.json();assert.deepEqual(data.attributes,[]);assert.ok(!JSON.stringify(data).includes('Legendary'));});
test('confirmed mint reveals original artwork, thumbnail and rarity at the confirmed block',async()=>{const{handler,blocks}=setup();const art=await handler(req('/nft/art/001.svg'));assert.equal(await art.text(),record.svg);assert.equal(art.headers.get('cache-control'),'no-store');assert.equal(await(await handler(req('/nft/thumbs/001.webp'))).text(),'SECRET_THUMB');assert.deepEqual((await(await handler(req('/nft/metadata/1.json'))).json()).attributes,record.metadata.attributes);assert.deepEqual((await(await handler(req('/nft/revealed?ids=1,2'))).json()).entries,[record.entry]);assert.ok(blocks.every(b=>b==='0x63'));});
test('RPC outage and wrong network fail closed',async()=>{for(const opts of [{failure:true},{chain:'0x1'}]){const{handler}=setup(opts);for(const path of ['/nft/art/001.svg','/nft/metadata/1.json','/nft/revealed?ids=1']){const r=await handler(req(path));assert.equal(r.status,503);assert.ok(!(await r.text()).includes('SECRET'));}}});
test('private manifest, rarity mapping, malformed requests and excessive batches are rejected',async()=>{const{handler}=setup();for(const path of ['/nft/manifest.json','/nft/rarity.json','/nft/art/001.json'])assert.equal((await handler(req(path))).status,404);for(const path of ['/nft/art/301.svg','/nft/revealed?ids=0','/nft/revealed?ids='+Array.from({length:31},(_,i)=>i+1).join(',')])assert.equal((await handler(req(path))).status,400);});
test('current build contains no static collection or client-side rarity assignment',()=>{assert.equal(existsSync('dist/client/nft'),false);const js=readFileSync('dist/client/assets/app.js','utf8');assert.ok(!js.includes('clunk-edition-tiers-v1'));assert.ok(!js.includes('rarity_distribution'));assert.ok(!js.includes('clunk-everyday-experiments-v1'));});
test('built Worker serves frontend and blocks source/collection bypasses',async()=>{const worker=(await import('../../dist/server/index.js')).default;const env={ASSETS:{fetch:async r=>new Response(new URL(r.url).pathname==='/index.html'?'FRONTEND':'missing',{status:new URL(r.url).pathname==='/index.html'?200:404})}};assert.equal(await(await worker.fetch(req('/vaults'),env)).text(),'FRONTEND');for(const p of ['/private/nft/manifest.json','/server/index.js','/.git/config'])assert.equal((await worker.fetch(req(p),env)).status,404);assert.deepEqual((await(await worker.fetch(req('/nft/metadata/1.json'),env)).json()).attributes,[]);});
